# {{{
# Generated by zgen.
# This file will be overwritten the next time you run zgen save!

ZSH=/home/arafat/.zgen/robbyrussell/oh-my-zsh-master

# ### General modules
source "/home/arafat/.zgen/sevaho/Powerzeesh-master/powerzeesh.zsh-theme"
source "/home/arafat/.zgen/robbyrussell/oh-my-zsh-master/plugins/battery/battery.plugin.zsh"
source "/home/arafat/.zgen/robbyrussell/oh-my-zsh-master/plugins/nvm/nvm.plugin.zsh"
source "/home/arafat/.zgen/robbyrussell/oh-my-zsh-master/plugins/npm/npm.plugin.zsh"
source "/home/arafat/.zgen/robbyrussell/oh-my-zsh-master/plugins/copydir/copydir.plugin.zsh"
source "/home/arafat/.zgen/robbyrussell/oh-my-zsh-master/plugins/cp/cp.plugin.zsh"
source "/home/arafat/.zgen/robbyrussell/oh-my-zsh-master/plugins/tmux/tmux.plugin.zsh"
source "/home/arafat/.zgen/robbyrussell/oh-my-zsh-master/plugins/sudo/sudo.plugin.zsh"
source "/home/arafat/.zgen/robbyrussell/oh-my-zsh-master/plugins/colored-man-pages/colored-man-pages.plugin.zsh"
source "/home/arafat/.zgen/robbyrussell/oh-my-zsh-master/plugins/git/git.plugin.zsh"
source "/home/arafat/.zgen/robbyrussell/oh-my-zsh-master/plugins/rsync/rsync.plugin.zsh"
source "/home/arafat/.zgen/robbyrussell/oh-my-zsh-master/plugins/screen/screen.plugin.zsh"
source "/home/arafat/.zgen/zsh-users/zsh-syntax-highlighting-master/zsh-syntax-highlighting.plugin.zsh"

# ### Plugins & Completions
fpath=(/home/arafat/.zgen/sevaho/Powerzeesh-master /home/arafat/.zgen/robbyrussell/oh-my-zsh-master/plugins/battery /home/arafat/.zgen/robbyrussell/oh-my-zsh-master/plugins/nvm /home/arafat/.zgen/robbyrussell/oh-my-zsh-master/plugins/npm /home/arafat/.zgen/robbyrussell/oh-my-zsh-master/plugins/copydir /home/arafat/.zgen/robbyrussell/oh-my-zsh-master/plugins/cp /home/arafat/.zgen/robbyrussell/oh-my-zsh-master/plugins/tmux /home/arafat/.zgen/robbyrussell/oh-my-zsh-master/plugins/sudo /home/arafat/.zgen/robbyrussell/oh-my-zsh-master/plugins/colored-man-pages /home/arafat/.zgen/robbyrussell/oh-my-zsh-master/plugins/git /home/arafat/.zgen/robbyrussell/oh-my-zsh-master/plugins/rsync /home/arafat/.zgen/robbyrussell/oh-my-zsh-master/plugins/screen /home/arafat/.zgen/zsh-users/zsh-syntax-highlighting-master ${fpath})

# }}}
